### ISSUE TITLE
infinite scroller is not working when i added this module .

### ISSUE THREAD

**Issue by ajaykumarReddy** [orizens/angular2-infinite-scroll#3]
I am getting browser console error like

nhandled Promise rejection: (SystemJS) Unexpected token <
	SyntaxError: Unexpected token <
	    at eval (<anonymous>)
	    at Object.eval (https://portal.mingledev.infor.com:9443/Scripts/generated/main.js:14:29)
	    at eval (https://portal.mingledev.infor.com:9443/Scripts/generated/main.js:43:4)
	    at eval (https://portal.mingledev.infor.com:9443/Scripts/generated/main.js:44:3)
	    at eval (<anonymous>)
	Evaluating https://portal.mingledev.infor.com:9443/ngx-infinite-scroll
	Evaluating https://portal.mingledev.infor.com:9443/Scripts/generated/main.js

**Comment by majormark** [comment]
I have occurred same problem, 
it's because the response include html mark, but what you need is javascript.
you may need to adjust the version of SystemJs.

"systemjs": "0.19.41"
"systemjs-builder": "0.15.34"
"@ types/systemjs": "^0.19.31"
the above version works for me
