### ISSUE TITLE
Error: Can't resolve all parameters for InfiniteScroll

### ISSUE THREAD

**Issue by marcalj** [orizens/angular2-infinite-scroll#30]
Any hint about this error? It was working in the last version, after update it shows this:

```
"Error: Can't resolve all parameters for InfiniteScroll: (?).
    at new BaseException (http://localhost:9100/node_modules/@angular/compiler/src/facade/exceptions.js:20:23)
    at CompileMetadataResolver.getDependenciesMetadata (http://localhost:9100/node_modules/@angular/compiler/src/metadata_resolver.js:295:19)
    at CompileMetadataResolver.getTypeMetadata (http://localhost:9100/node_modules/@angular/compiler/src/metadata_resolver.js:174:26)
    at CompileMetadataResolver.getDirectiveMetadata (http://localhost:9100/node_modules/@angular/compiler/src/metadata_resolver.js:138:28)
    at Array.map (native)
    at eval (http://localhost:9100/node_modules/@angular/compiler/src/runtime_compiler.js:84:63)
    at Array.forEach (native)
    at RuntimeCompiler._compileComponent (http://localhost:9100/node_modules/@angular/compiler/src/runtime_compiler.js:81:36)
    at eval (http://localhost:9100/node_modules/@angular/compiler/src/runtime_compiler.js:71:49)
    at run (http://localhost:9100/node_modules/core-js/client/shim.js:4016:23)"
```

**Comment by marcalj** [comment]
Duplicate of #28
